#!/bin/sh

# Install system package dependencies
sudo apt install -y npm ffmpeg bluetooth bluez libbluetooth-dev libudev-dev

# Configure npm directory and install npm package
npm config set prefix '~/.npm'
npm install -g twitch-powered-up

# Allow BLE permissions
sudo setcap cap_net_raw+eip $(eval readlink -f $(which node))

# Add binary to PATH
export PATH=$HOME/.npm/bin:$PATH
echo "export PATH=$HOME/.npm/bin:$PATH" >> ~/.profile
source ~/.profile
